
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: sport-mgmt-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sport_mgmt
    # --- Additional database service configurations ---
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: sport-mgmt-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://devuser:devpassword@db:5432/sport-mgmt-db
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules

volumes:
  postgres_data:
  node_modules: